# Generated by Django 2.2.5 on 2019-09-20 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=70)),
                ('year', models.IntegerField()),
                ('vin', models.CharField(max_length=17, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cars',
                'ordering': ['make', 'car_model'],
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order_amount', models.PositiveIntegerField()),
                ('order_status', models.CharField(choices=[('COMP', 'Completed'), ('INPR', 'In Progress'), ('CANC', 'Cancelled')], max_length=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='Station_management.Cars')),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='cars',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cars', to='Station_management.Clients'),
        ),
    ]
