# Generated by Django 2.2.5 on 2019-09-23 22:34

import Station_management.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Station_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='make',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Please use only latin letters.', regex='[A-Za-z]')]),
        ),
        migrations.AlterField(
            model_name='cars',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='Cars', to='Station_management.Clients'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='vin',
            field=models.CharField(max_length=17, unique=True, validators=[Station_management.validators.vin_validator]),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.IntegerField(validators=[Station_management.validators.year_validator]),
        ),
        migrations.AlterField(
            model_name='clients',
            name='first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Please use only latin letters.', regex='[A-Za-z]')]),
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Please use only latin letters.', regex='[A-Za-z]')]),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(validators=[Station_management.validators.order_date_validator]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_amount',
            field=models.IntegerField(validators=[Station_management.validators.order_amount_validator]),
        ),
    ]
